name: Deploy To Production

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Docker image tag to environment
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Retrieve latest image from ACR
        run: docker pull ${{ secrets.REGISTRY_NAME }}/staging:latest

      - name: Retag image as latest image
        run: docker tag ${{ secrets.REGISTRY_NAME }}/staging:latest ${{ secrets.REGISTRY_NAME }}/production:latest

      - name: Retag image for archiving using current datetime
        run: docker tag ${{ secrets.REGISTRY_NAME }}/staging:latest ${{ secrets.REGISTRY_NAME }}/production:$IMAGE_TAG

      - name: Push latest image to production
        run: docker push ${{ secrets.REGISTRY_NAME }}/production:latest

      - name: Push archive image to production
        run: docker push ${{ secrets.REGISTRY_NAME }}/production:$IMAGE_TAG
